### PR TITLE
Check auctions ended endpoint to remove any ended auctions from list + General code cleanup

### PR DESCRIPTION
**Pull request by Barragek0**

### CODE REVIEW

**Comment by Vikame** [comment]
Oops, sorry for the accidental mark as ready for review. Just a misclick. Thanks for the contribution though! I'll look through this once it's ready.

**Comment by Vikame** [comment]
This likely should be noted somewhere in the README for the project, but I would like to ensure the use of the google java format within the project. Not the fault of yourself, but just something I forgot to mention previously.

**Comment by Barragek0** [comment]
Seems like this isnt working as intended currently, not sure if I made a mistake in the code or not, will take another look later.

**Comment by Barragek0** [comment]
Going to close this as it seems like the auctions_ended endpoint updates once a minute, like the normal auctions endpoint so doing this is pointless :/

**Pull request closed without merging**
